
	USE [master]
	GO

	/****** Object:  Database [Supermarket]    Script Date: 9/22/2021 11:02:23 PM ******/
	CREATE DATABASE [Supermarket]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'Supermarket', FILENAME = N'/var/opt/mssql/data/Supermarket.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
	 LOG ON 
	( NAME = N'Supermarket_log', FILENAME = N'/var/opt/mssql/data/Supermarket_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
	 WITH CATALOG_COLLATION = DATABASE_DEFAULT
	GO

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [Supermarket].[dbo].[sp_fulltext_database] @action = 'enable'
	end
	GO

	ALTER DATABASE [Supermarket] SET ANSI_NULL_DEFAULT OFF 
	GO

	ALTER DATABASE [Supermarket] SET ANSI_NULLS OFF 
	GO

	ALTER DATABASE [Supermarket] SET ANSI_PADDING OFF 
	GO

	ALTER DATABASE [Supermarket] SET ANSI_WARNINGS OFF 
	GO

	ALTER DATABASE [Supermarket] SET ARITHABORT OFF 
	GO

	ALTER DATABASE [Supermarket] SET AUTO_CLOSE OFF 
	GO

	ALTER DATABASE [Supermarket] SET AUTO_SHRINK OFF 
	GO

	ALTER DATABASE [Supermarket] SET AUTO_UPDATE_STATISTICS ON 
	GO

	ALTER DATABASE [Supermarket] SET CURSOR_CLOSE_ON_COMMIT OFF 
	GO

	ALTER DATABASE [Supermarket] SET CURSOR_DEFAULT  GLOBAL 
	GO

	ALTER DATABASE [Supermarket] SET CONCAT_NULL_YIELDS_NULL OFF 
	GO

	ALTER DATABASE [Supermarket] SET NUMERIC_ROUNDABORT OFF 
	GO

	ALTER DATABASE [Supermarket] SET QUOTED_IDENTIFIER OFF 
	GO

	ALTER DATABASE [Supermarket] SET RECURSIVE_TRIGGERS OFF 
	GO

	ALTER DATABASE [Supermarket] SET  DISABLE_BROKER 
	GO

	ALTER DATABASE [Supermarket] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	GO

	ALTER DATABASE [Supermarket] SET DATE_CORRELATION_OPTIMIZATION OFF 
	GO

	ALTER DATABASE [Supermarket] SET TRUSTWORTHY OFF 
	GO

	ALTER DATABASE [Supermarket] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	GO

	ALTER DATABASE [Supermarket] SET PARAMETERIZATION SIMPLE 
	GO

	ALTER DATABASE [Supermarket] SET READ_COMMITTED_SNAPSHOT OFF 
	GO

	ALTER DATABASE [Supermarket] SET HONOR_BROKER_PRIORITY OFF 
	GO

	ALTER DATABASE [Supermarket] SET RECOVERY FULL 
	GO

	ALTER DATABASE [Supermarket] SET  MULTI_USER 
	GO

	ALTER DATABASE [Supermarket] SET PAGE_VERIFY CHECKSUM  
	GO

	ALTER DATABASE [Supermarket] SET DB_CHAINING OFF 
	GO

	ALTER DATABASE [Supermarket] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	GO

	ALTER DATABASE [Supermarket] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	GO

	ALTER DATABASE [Supermarket] SET DELAYED_DURABILITY = DISABLED 
	GO

	ALTER DATABASE [Supermarket] SET ACCELERATED_DATABASE_RECOVERY = OFF  
	GO

	ALTER DATABASE [Supermarket] SET QUERY_STORE = OFF
	GO

	ALTER DATABASE [Supermarket] SET  READ_WRITE 
	GO

